package com.linkedin.post.mapper;

import com.linkedin.post.dto.CommentResponseDto;
import com.linkedin.post.dto.CreateCommentRequest;
import com.linkedin.post.dto.UpdateCommentRequest;
import com.linkedin.post.model.Comment;
import org.mapstruct.*;

import java.util.List;

/**
 * MapStruct Mapper for Comment entity ↔ DTO conversion.
 * 
 * Purpose:
 * Automatically generates code for converting between:
 * - Comment entity (database) ↔ CommentResponseDto (API response)
 * - CreateCommentRequest (API request) ↔ Comment entity
 * 
 * Supports nested comment structure (Composite Pattern):
 * - Root comments (parentCommentId = null)
 * - Replies (parentCommentId = X)
 * - Nested replies (parentCommentId = Y, where Y is a reply)
 * 
 * Usage Example:
 * <pre>
 * {@code
 * @Service
 * public class CommentService {
 *     @Autowired
 *     private CommentMapper commentMapper;
 *     
 *     public CommentResponseDto getComment(Long id) {
 *         Comment comment = commentRepository.findById(id).orElseThrow();
 *         return commentMapper.toDto(comment);
 *     }
 *     
 *     public Comment createComment(CreateCommentRequest request, Long postId, Long authorId) {
 *         Comment comment = commentMapper.toEntity(request);
 *         comment.setPostId(postId);
 *         comment.setAuthorId(authorId);
 *         return commentRepository.save(comment);
 *     }
 * }
 * }
 * </pre>
 * 
 * @see Comment
 * @see CommentResponseDto
 * @see CreateCommentRequest
 */
@Mapper(
    componentModel = "spring",
    unmappedTargetPolicy = ReportingPolicy.IGNORE,
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
public interface CommentMapper {

    // =========================================================================
    // Entity → Response DTO (Database → API Response)
    // =========================================================================
    
    /**
     * Convert Comment entity to CommentResponseDto.
     * 
     * Automatic Mappings:
     * - id → id
     * - postId → postId
     * - content → content
     * - parentCommentId → parentCommentId
     * - likesCount → likesCount
     * - repliesCount → repliesCount
     * - isEdited → isEdited (renamed from 'edited')
     * - editedAt → editedAt
     * - createdAt → createdAt
     * - updatedAt → updatedAt
     * 
     * Custom Mappings:
     * - isRootComment (computed from parentCommentId)
     * 
     * Manual Enrichment (in service layer):
     * - author (from User Service)
     * - hasLiked (from Like repository)
     * - isAuthor (business logic)
     * - canEdit, canDelete (business logic)
     * - replies (loaded separately on demand)
     * 
     * @param comment Comment entity
     * @return CommentResponseDto
     */
    @Mapping(source = "edited", target = "isEdited")
    @Mapping(target = "isRootComment", expression = "java(comment.isRootComment())")
    @Mapping(target = "author", ignore = true) // Enriched in service
    @Mapping(target = "hasLiked", ignore = true) // Computed in service
    @Mapping(target = "isAuthor", ignore = true) // Computed in service
    @Mapping(target = "canEdit", ignore = true) // Computed in service
    @Mapping(target = "canDelete", ignore = true) // Computed in service
    @Mapping(target = "replies", ignore = true) // Loaded separately
    CommentResponseDto toDto(Comment comment);
    
    /**
     * Convert list of Comment entities to list of CommentResponseDtos.
     * 
     * Batch mapping for collections.
     * 
     * @param comments List of Comment entities
     * @return List of CommentResponseDtos
     */
    List<CommentResponseDto> toDtoList(List<Comment> comments);

    // =========================================================================
    // Request DTO → Entity (API Request → Database)
    // =========================================================================
    
    /**
     * Convert CreateCommentRequest to Comment entity.
     * 
     * Automatic Mappings:
     * - content → content
     * - parentCommentId → parentCommentId
     * 
     * Fields set by service:
     * - id (auto-generated by database)
     * - postId (from URL parameter)
     * - authorId (from JWT token)
     * - engagement counts (initialized to 0)
     * - edited flags (initialized to false)
     * - audit fields (auto-populated by JPA)
     * 
     * @param request CreateCommentRequest
     * @return Comment entity (partially populated)
     */
    @Mapping(target = "id", ignore = true) // Auto-generated
    @Mapping(target = "postId", ignore = true) // Set in service
    @Mapping(target = "authorId", ignore = true) // Set in service
    @Mapping(target = "likesCount", constant = "0")
    @Mapping(target = "repliesCount", constant = "0")
    @Mapping(target = "edited", constant = "false")
    @Mapping(target = "editedAt", ignore = true)
    @Mapping(target = "deleted", constant = "false")
    @Mapping(target = "deletedAt", ignore = true)
    @Mapping(target = "createdAt", ignore = true) // Auto-populated by JPA
    @Mapping(target = "updatedAt", ignore = true) // Auto-populated by JPA
    Comment toEntity(CreateCommentRequest request);
    
    /**
     * Update existing Comment entity from UpdateCommentRequest.
     * 
     * Only updates:
     * - content
     * - Sets edited flag to true
     * - Sets editedAt to current time (done in service)
     * 
     * All other fields remain unchanged.
     * 
     * @param request UpdateCommentRequest
     * @param comment Existing Comment entity (will be modified)
     */
    @Mapping(target = "id", ignore = true) // Never change ID
    @Mapping(target = "postId", ignore = true) // Never change post
    @Mapping(target = "authorId", ignore = true) // Never change author
    @Mapping(target = "parentCommentId", ignore = true) // Structure is immutable
    @Mapping(target = "likesCount", ignore = true) // Don't reset counts
    @Mapping(target = "repliesCount", ignore = true)
    @Mapping(target = "edited", ignore = true) // Set manually in service
    @Mapping(target = "editedAt", ignore = true) // Set manually in service
    @Mapping(target = "deleted", ignore = true) // Don't change delete status
    @Mapping(target = "deletedAt", ignore = true)
    @Mapping(target = "createdAt", ignore = true) // Don't change creation time
    @Mapping(target = "updatedAt", ignore = true) // Auto-updated by JPA
    void updateEntity(UpdateCommentRequest request, @MappingTarget Comment comment);
}

