package com.linkedin.connection.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for connection suggestions ("People You May Know").
 * Provides recommendations for users to connect with.
 * 
 * Design Considerations:
 * - Includes reason for suggestion (mutual connections, same industry, etc.)
 * - Shows the number of mutual connections
 * - Includes relevant user profile info
 * - Optimized for quick decision-making
 * 
 * Suggestion Algorithm (handled by SuggestionStrategy):
 * - Mutual connections: "5 mutual connections"
 * - Same industry: "Also works in Software Engineering"
 * - Same company: "Works at Google"
 * - Same location: "Based in San Francisco"
 * 
 * Example Usage (JSON Response Body):
 * <pre>
 * {@code
 * {
 *   "userId": 789,
 *   "name": "Alex Johnson",
 *   "headline": "Senior Engineer at Microsoft",
 *   "profilePictureUrl": "https://example.com/avatar/alex.jpg",
 *   "mutualConnections": 12,
 *   "suggestionReason": "You both have 12 mutual connections",
 *   "location": "Seattle, WA",
 *   "accountType": "PREMIUM"
 * }
 * }
 * </pre>
 * 
 * @see com.linkedin.connection.controller.ConnectionController#getConnectionSuggestions
 * @see com.linkedin.connection.patterns.strategy.SuggestionStrategy
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(description = "DTO for connection suggestions (People You May Know)")
public class ConnectionSuggestionDto {

    /**
     * ID of the suggested user.
     */
    @Schema(description = "User ID of the suggested connection", example = "789")
    private Long userId;

    /**
     * Full name of the suggested user.
     */
    @Schema(description = "User's full name", example = "Alex Johnson")
    private String name;

    /**
     * Professional headline.
     */
    @Schema(description = "User's professional headline", example = "Senior Engineer at Microsoft")
    private String headline;

    /**
     * Profile picture URL.
     */
    @Schema(description = "User's profile picture URL", example = "https://example.com/avatar/alex.jpg")
    private String profilePictureUrl;

    /**
     * Number of mutual connections.
     */
    @Schema(description = "Number of mutual connections", example = "12")
    private Integer mutualConnections;

    /**
     * Reason why this user is being suggested.
     * Generated by the suggestion algorithm.
     */
    @Schema(
        description = "Reason for the suggestion",
        example = "You both have 12 mutual connections"
    )
    private String suggestionReason;

    /**
     * User's location (helps identify local connections).
     */
    @Schema(description = "User's location", example = "Seattle, WA")
    private String location;

    /**
     * Account type (BASIC or PREMIUM).
     */
    @Schema(description = "User's account type", example = "PREMIUM")
    private String accountType;

    /**
     * Score indicating suggestion strength (higher = better match).
     * Used for ranking suggestions.
     * Not exposed to client (internal use only).
     */
    @Schema(hidden = true)
    private Double suggestionScore;
}

